config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :clientes

  get 'welcome/index'

  resources :productos
  
  root 'welcome#index' 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :productos       
end

app/models/detalle_compra.rb
class DetalleCompra < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
end

app/models/producto.rb
class Producto < ApplicationRecord
	belongs_to :cliente 
	validates :codigo, presence: true, uniqueness: true
	validates :nombre, presence: true, length: { minimum: 5}
end

app/models/proveedor.rb
class Proveedor < ApplicationRecord
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
	
	def index
		@producto = Producto.all
	end 
	#GET/articles/id
	def show
		@producto = Producto.find(params[:id])
	end
	#GET/articles/new
	def new
		@producto = Producto.new
	end
	def create
		@producto = current_user.productos.new(producto_params)
		if @producto.save
			redirect_to @producto
		else
			render :new
		end
		
	end
	def edit
		@producto = Producto.find(params[:id])
	end
	def update
		@producto = Producto.find(params[:id])
		if @producto.update(producto_params)
			redirect_to @producto
		else
			render :edit
		end
	end
	def destroy
		@producto = Productofind(params[:id])
		@producto.destroy
		redirect_to productos_path
	end
	private


	def producto_params
		params.require(:producto).permit(:codigo,:nombre)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= render "partials/navigation"%>
<p class="notice"><%= notice %></p>
  <p classs="alert"><%= alert%></p>

    <%= yield %>
  </body>
</html>

app/views/partials/_navigation.html.erb
<header>
	<nav class="be-red white large-padding">
		<ul class="row center-xs center-xs middle-xs">
			<li class="col-md">
				<h1 class="no-margin" id="logo">Blog </h1> 
			</li>
			<li class="col-md">
				 <%= link_to "Inicio", root_path %>
			</li>
			<li class="col-md">
				<%= link_to "Productos", productos_path %>
			</li>
			
				
			<li class="col-md">
			<% if cliente_signed_in? %>
				<li class="col-md">
					<%= link_to "Cerrar sesión", destroy_cliente_session_path, method: :delete, class:"be-red white"%>
				</li>
			<%else%>
				<li class="col-md">
					<%= link_to "Iniciar sesión", new_cliente_session_path, class:"be-red white"%>
				</li>
				<li class="col-md">
					<%= link_to "Crear cuenta", new_cliente_registration_path, class:"be-red white"%>
				</li>
			</li>
			<%end%>
		</ul>
	</nav>
</header>  

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
	<% @producto.errors.full_messages.each do |message| %>
		<div class="be-red white top-space">
			* <%= message %>
		</div>
	<%end%>
	<div class="field">
		<%= f.text_field :nombre, placeholder: "Ingrese el nombre del producto", class:"form-control"%>
	</div class="field">
	<div>
		<%= f.text_area :codigo, placeholder: "Escribir el codigo del producto", style: "height: 250px;", class:"form-control"%>
	</div>
	<div class="field">
		<%= f.submit "Guardar", class:"btn be-red white"%>
		</div>
<%end%>	

app/views/productos/edit.html.erb
<div style="width: 80%; margin: 0 auto;">
	<h1> Editar Articulo</h1>
	<%= render "form" %>
</div>

app/views/productos/index.html.erb
<% @producto.each do |producto| %>
	<h1> <%= link_to producto.nombre, producto %></h1>
	<div>
		<%= producto.codigo%> - <%= link_to "Eliminar", producto, method: :delete, class:"red"%>
	</div>
<%end%>

app/views/productos/new.html.erb
<div style="width: 80%; margin: 0 auto;">
	<h1> Crear Articulo</h1>
	<%= render "form" %>
</div>

app/views/productos/show.html.erb
<h1> <%= @producto.nombre %></h1>
<% unless @producto.cliente.nil? %>
<p>
	Escrito por: <%= @producto.cliente.email %>
</p>
<%end%>
<div>
	<%= @producto.codigo%>
</div>
<div>
	<%= link_to "Editar", edit_producto_path(@producto), class:"be-red white "%>

</div>

app/views/welcome/index.html.erb
<%if cliente_signed_in? %>
	<hl>Bienvenido <%= current_cliente.email %></hl>
<%end %>